### ISSUE TITLE
iOS - Wrong download location?

### ISSUE THREAD

**Issue by vernondegoede** [phonegap/phonegap-plugin-contentsync#120] opened 2016-04-14 11:08 UTC
In the documentation it states that the plugin stores the synced content in the `cordova.file.dataDirectory` path from the cordova-plugin-file package. 

I'm using the following code the download my file:

```
downloadFile: function (url, fileName) {
        var sync = ContentSync.sync({
            src: url,
            id: 'image-' + fileName,
            type: 'local'
        });

        sync.on('progress', function (data) {
            console.log('progress', data.progress);
        });

        sync.on('complete', function (data) {

            window.resolveLocalFileSystemURL("file://" + data.localPath, function (entry) {
                // entry is a DirectoryEntry object
                console.log('entry in DirectoryEntry', entry);
            }, function (error) {
                console.log("Error: " + error.code);
            });

            var imageTag = document.createElement('img'),
                imageArea = document.getElementsByClassName('image-area');

            imageTag.setAttribute('width', '100px');
            imageTag.setAttribute('height', '100px');
            imageTag.setAttribute("src", data.localPath);

            imageArea[0].appendChild(imageTag);
        });

        sync.on('error', function (e) {
            console.log('error', e);
        });

        sync.on('cancel', function () {
            // triggered if event is cancelled
            console.log('Cancelled!');
        });
    }
```

This should mean that the files should be downloaded to `Library/NoCloud/`. However, in Xcode it seems the files are downloaded to the `Library` folder. 

Here's a snippet from the Xcode console:

```
2016-04-14 12:14:18.845 Cravt B2B[82496:26895163] Moving /Users/vernon/Library/Developer/CoreSimulator/Devices/8F22FA0B-7899-4185-BF3D-9B9DF93F8221/data/Containers/Data/Application/A74492DC-FD7A-4D3F-B1B5-5B5A05EEDEA2/Library/320243.png to /Users/vernon/Library/Developer/CoreSimulator/Devices/8F22FA0B-7899-4185-BF3D-9B9DF93F8221/data/Containers/Data/Application/A74492DC-FD7A-4D3F-B1B5-5B5A05EEDEA2/Library/image-257
```

**Comment by vernondegoede** [comment] 2016-04-14 12:48
Nevermind, this only seems to be the case when using the iOS Simulator. On real devices the files are stored in `Libarary/NoCloud` 

close

**Comment by vernondegoede** [comment] 2016-04-19 10:29
It seems I was wrong. This actually seems to be the case everywhere. What am I doing wrong?

In the documentation it states that files should be downloaded to the `NoCloud` folder. However, my files are still stored in the `Library` folder.

Snippet of my config.xml:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.coqtail.cravtb2b" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
...
    <content src="index.html" />
    <preference name="iosPersistentFileLocation" value="Library" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="Orientation" value="landscape" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <preference name="exit-on-suspend" value="false" />
...
```

**Comment by timkim** [comment] 2016-04-19 22:20
Hi @vernondegoede 

Hrmm, I have a feeling that these two preferences might be the cause of your problems: 
```
    <preference name="iosPersistentFileLocation" value="Library" />
    <preference name="BackupWebStorage" value="none" />
```

Try taking those out and see if that works.

**Comment by vernondegoede** [comment] 2016-04-21 12:13
Hi @timkim ,

I did set those options, actually. Didn't make any difference though. I stopped using ContentSync after these errors. I switched to native file transfer download, which did work.

Unfortunately, I don't have time to look into the issue again. Sorry!

**Comment by timkim** [comment] 2016-04-21 20:10
Hi again @vernondegoede,

Hrm weird. Well, I guess I can close this issue then :P

**Closed by timkim** 2016-04-21 20:10 UTC
