### ISSUE TITLE
Can't download on ipad

### ISSUE THREAD

**Issue by wroquet** [phonegap/phonegap-plugin-contentsync#37] opened 2015-06-17 13:55 UTC
I use this plugin in my cordova project to download a zip of images, works fine on emulator, but i encounter problems in a real device : 

the download time out after around 20 seconds with the following error : 
<__NSCFBackgroundDownloadTask: 0x16691bc0> completed with error: The request timed out.
here is my snippet code :
http://pastebin.com/rJmj7BUh

my logs on the "progress" event shows negative progress, it's normal ? : 
![capture d ecran 2015-06-17 a 15 47 14](https://cloud.githubusercontent.com/assets/4560722/8208507/460b2602-1508-11e5-9c0b-d8d3297df656.png)

**Comment by kaansoral** [comment] 2015-06-17 14:50
It works for my with the simulator and an ipod, but let me test with an ipad too, what is your ipad model / os version?

**Comment by wroquet** [comment] 2015-06-17 15:31
i'm on an Ipad 2 with IOS 7

**Comment by imhotep** [comment] 2015-06-17 22:34
@wroquet Can you share the URL to the archive (or another archive that triggers this issue) ? There shouldn't be any negative values for progress. I wasn't able to reproduce your problem.

**Comment by macdonst** [comment] 2015-06-18 16:30
@wroquet Two things, 1) how big is the file you are attempting to download? and 2) can you re-test with the latest version (1.1.2) of the content sync plugin?

**Comment by revolunet** [comment] 2015-07-08 09:42
@macdonst is there a size limitation or known issues with large files on iOS ?

**Comment by macdonst** [comment] 2015-07-08 19:03
@revolunet actually, there was a problem where the iOS download would stop after 30 seconds. We've since fixed this issue and I've downloaded over 500 mb over a slow connection. We just wanted to get more info in order to track this problem down. I'm pretty sure this issue is fixed but I'm hoping to hear back from @wroquet before closing.

**Comment by revolunet** [comment] 2015-07-08 22:01
Awesome thanks

**Closed** 2016-06-07 14:27 UTC
Labels: ios
